include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Escuela
Escuela_HEADERS = Alumno.h Materia.h Calificacion.h
Escuela_OBJC_FILES = main.m Alumno.m Materia.m Calificacion.m
Escuela_RESOURCE_FILES =

include $(GNUSTEP_MAKEFILES)/application.make