include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Calculadora
Calculadora_HEADERS = Calculator.h
Calculadora_OBJC_FILES = main.m Calculator.m
Calculadora_RESOURCE_FILES =

include $(GNUSTEP_MAKEFILES)/application.make