include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Carro
Carro_HEADERS = Car.h AppDelegate.h Racecar.h
Carro_OBJC_FILES = AppDelegate.m Car.m Racecar.m
Carro_RESOURCE_FILES =

include $(GNUSTEP_MAKEFILES)/application.make