include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Personitas
Personitas_HEADERS = Personita.h
Personitas_OBJC_FILES = main.m Personita.m
Personitas_RESOURCE_FILES =

include $(GNUSTEP_MAKEFILES)/application.make
